### ISSUE TITLE
MIgrate Heron project to GitHub

### ISSUE THREAD

**Issue by GoogleCodeExporter** [heron-mc/heron-mc#417]
```
Google Code is shutting down: 
http://google-opensource.blogspot.nl/2015/03/farewell-to-google-code.html

Best option is to migrate to GitHub. GC provides an exporter tool, but several 
other actions need to be taken:

* create Organization  on GH (DONE)

* map GC accounts to GH account (4 lacking)

* update build post-commit hook

* use GH Milestone convention (is in GC Wiki page)

* migrate Wiki

* all references/links to GC --> GH

* possibly subproject for Heron apps?

* svn-externals: to GitHub submodules

* guidance to users

* documentation/website updates

Add more things to do here!


```

Original issue reported on code.google.com by `jus...@gmail.com` on 25 Mar 2015 at 11:28

**Comment by justb4** [comment]
Notice: migration of the Heron project from Google Code to GitHub is now in progress. Please do not use the Google Code issue tracker, or commit any code. The mailing list will remain as-is. Further messages will follow. See https://github.com/heron-mc/heron-mc for the new home. Use the GitHub issue tracker there. Will notice further once migration has completed, but so far so good....

**Comment by justb4** [comment]
Current status of things to do:

* create Organization  on GH (DONE)

* map GC accounts to GH account (DONE but somehow not complete infos)

* update build post-commit hook (DONE)

* use GH Milestone convention (TODO)

* migrate Wiki (DONE)

* all references/links to GC --> GH (DONE, needs check)

* possibly subproject for Heron apps? (DONE, not now)

* svn-externals: to GitHub submodules (DONE)

* guidance to users (TODO)

* documentation/website updates (DONE, needs check)

**Comment by justb4** [comment]
This is now completed, closing...
