### ISSUE TITLE
Detail view in featureinfopanel problem with empty fields

### ISSUE THREAD

**Issue by wimblanken** [heron-mc/heron-mc#422]
Hi Just,

Had a problem with the switching between table and detail view in the featureinfopanel. After some research i acknowledged that layers with empty fields do not show in the detail view. I solved it using the following code (in displayvertical) by checking if sourceStore[column.dataIndex]!=null . Now it is working OK. 

if (column.id != 'btn_detail') {
                    if (column.renderer) {
		       if (sourceStore[column.dataIndex]!=null) {
                        value = column.renderer(sourceStore[column.dataIndex], null, this.mainPanel.items.items[0].store.data.items[this.propGrid.curRecordNr]);
			}
                    } else {
                        value = sourceStore[column.dataIndex];
                    }
                    var rec = new Ext.grid.PropertyRecord({
                        name: column.header,
                        value: value
                    });
                    this.propGrid.store.add(rec);
                }

Greetings

Wim

**Comment by RinkeHeida** [comment]
Hi Wim,

Do you have an online WMS showing this behavior?
In order to reproduce the problem and test the solution would save some time.

Greetings
Rinke

**Comment by wimblanken** [comment]
Dag Rinke,

 

Volgens mij kun je de WMS wel gebruiken met Rijksmonumenten. Die heeft lege velden.

 

http://bevinggevoeld.nl/cgi-bin/mapserv?map=/var/www/mapfiles/test.map&LAYERS=rijksmonumenten&FORMAT=image%2Fpng&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&SRS=EPSG%3A28992&BBOX=23240,499617.6,466760,646382.4&WIDTH=2062&HEIGHT=682

 

Ik heb overigens Heron wel aangepast in het verleden vanwege de problemen die ik had met de getfeatureinfo op Mapserver (in plaats van Geoserver). Wellicht dat het hiermee wel van doen heeft.

Ik zal je die aanpassingen ook nog sturen zodra ik weer achter mijn vaste PC zit.

 

Groetjes

 

Wim

 

 

Van: RinkeHeida [mailto:notifications@github.com] 
Verzonden: maandag 27 juli 2015 14:53
Aan: heron-mc/heron-mc
CC: wimblanken
Onderwerp: Re: [heron-mc] Detail view in featureinfopanel problem with empty fields (#422)

 

Hi Wim,

Do you have an online WMS showing this behavior?
In order to reproduce the problem and test the solution would save some time.

Greetings
Rinke

**Comment by ankeur** [comment]
Hi Wim,

We can not reproduce the problem with the layer 'rijksmonumenten'. The layer shows both in table and detail view of the featureinfopanel. Empty fields like 'Naam'and 'Oorsprfunc' are shown as well, leaving the value empty.

Greetings,
Anke

**Comment by justb4** [comment]
Wim: problem solved or no problem? Then I can close this issue.

**Comment by wimblanken** [comment]
As Anke cannot reproduce it it must be a fault of my own changes. I will take a look this Christmas Holiday. But you can close it Just.
