### ISSUE TITLE
Zooming map not reload wms

### ISSUE THREAD

**Issue by gzkii27** [heron-mc/heron-mc#443]
Hi guys

I am testing a single map with Google maps service as background layer and wms service layer (Geoserver+Postgres), but zooming on the map not reload wms, 
please look this screenshot and my config file. Any idea?
![image](https://cloud.githubusercontent.com/assets/11275130/12127100/4685fed6-b3c3-11e5-89e6-a86aa969b652.png)

Config.js:

Ext.namespace("Heron");
OpenLayers.ProxyHost = "/cgi-bin/proxy.cgi?url=";

Heron.layout = {
	xtype: 'panel',
	id: 'hr-container-main',
	layout: 'border',

	items: [
		{
			xtype: 'panel',
			id: 'hr-menu-left-container',
			layout: 'accordion',
			region : "west",
			width: 240,
			collapsible: true,
			split	: true,
			border: false,
			items: [
				{
					xtype: 'hr_layertreepanel',
					contextMenu: [
						{
							xtype: 'hr_layernodemenulayerinfo'
						},
						{
							xtype: 'hr_layernodemenuzoomextent'
						},
						{
							xtype: 'hr_layernodemenuopacityslider'
						}
					],
					title: 'Layers'
				},

                {
                    xtype: 'hr_htmlpanel',
                    id: 'hr-info-west',
                    border: true,
					html: 'html test',
                    preventBodyReset: true,
                    title: 'Info'
                }
            ]
        },
		{
			xtype: 'panel',

			id: 'hr-map-and-info-container',
			layout: 'border',
			region: 'center',
			width: '100%',
			collapsible: true,
			split	: true,
			border: false,
			items: [
				{
					xtype: 'hr_mappanel',
					id: 'hr-map',
					region: 'center',
					collapsible : false,
					border: false,
					hropts: {
						settings :
						{
							projection: 'EPSG:900913',
							displayProjection: new OpenLayers.Projection("EPSG:900913"),
							units: 'm',
							maxExtent: '-8411534, -8383950, 949191, 925030',
							maxResolution: 31,
							xy_precision: 5,
							zoom: 8,
							center: '-8042553, 1274987',
							theme: null
						},

						layers : [
									new OpenLayers.Layer.Google(
											"Google Satellite",
											{type: google.maps.MapTypeId.SATELLITE, visibility: true},
											{singleTile: false, buffer: 0, isBaseLayer: true}

									),						
									new OpenLayers.Layer.WMS(
									"Poly",
									'http://192.168.85.127:8080/geoserver/gua2/wms?',
									{layers: "gua2:poly", myData: Math.random(), transparent: true, format: 'image/png'},
									{singleTile: true, opacity: 0.9, isBaseLayer: false, visibility: true, noLegend: false, transitionEffect: 'resize',minScale:0}
							)
							],
						toolbar: [
							{type: "featureinfo", options: {							}},
							{type: "-"} ,
							{type: "pan"},
							{type: "zoomprevious"},
							{type: "zoomnext"},
							{type: "-"},
							{type: "measurelength", options: {geodesic: true}},
							{type: "measurearea", options: {geodesic: true}},
							{type: "-"},
							{type: "addbookmark"},
							{type: "help", options: {tooltip: 'Help and info for this example', contentUrl: 'help.html'}},
						]
					}
				}			
			]
		}
	]
};

**Comment by el486** [comment]
Hi!
Maybe this behavior is caused for the option "resize" in the layer config. Try this:

```javascript
new OpenLayers.Layer.WMS("Limpiezas Cooperativas",wmsURL,
{layers: 'dipsoh:LimpiezaCooperativas2015',transparent: true, format:'image/png', singleTile: true },
                        {visibility: false, displayInLayerSwitcher:true, featureInfoFormat: 'application/vnd.ogc.gml',metadata: {
					wfs: {
						protocol: 'fromWMSLayer',
						downloadFormats:Heron.options.wfs.downloadFormats
						}
					}
			}
		),
```

**Comment by gzkii27** [comment]
Hi!
I try your recommendation.see this layer config:

new OpenLayers.Layer.WMS("Poly",'http://192.168.85.127:8080/geoserver/gua2/wms?',
										{layers: "gua2:poly", transparent: true, format: 'image/png', singleTile: true},
										{singleTile: true, isBaseLayer: false, visibility: true, displayInLayerSwitcher:true}
									)

but in this case layer disappears at minimal scales (8 or bigger). mmm i think transitioneffect label require other value. Any idea?. Thanks el486 Happy new year

**Comment by el486** [comment]
Here are my map settings:

```javascript
projection: 'EPSG:900913',
displayProjection: new OpenLayers.Projection("EPSG:22195"),
units: 'm',
tileSize: new OpenLayers.Size(256, 256),
maxResolution:2445.984904688, 
numZoomLevels: 12,
center: '-6500000, -4500000',
xy_precision: 2,
zoom: 7
```
As i see, your MaxResolution seems to be very low. Try commenting the line or setting a higher value

**Comment by gzkii27** [comment]
Hi 
I try again and nothing :(, my map setting is this now:

projection: 'EPSG:900913',
displayProjection: new OpenLayers.Projection("EPSG:3116"),
units: 'm',
tileSize: new OpenLayers.Size(256, 256),
maxResolution:2445,
numZoomLevels: 12,
maxExtent: '-8411534, -8383950, 949191, 925030',
center: '-8042553, 1274987',
xy_precision: 2,
zoom: 7

I use EPSG:3116 because is more appropriate for this data.
Possibly this issue is associated to the fact that when i use google maps displayProjection is ignored and my map continue in EPSG:900913 regardless of displayProjection setting

I try loading this wms in QGis and work fine when zooming.

Here are my html file also:
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
		"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
	<title>Test</title>

	
	<link rel="stylesheet" type="text/css" href="http://cdnjs.cloudflare.com/ajax/libs/extjs/3.4.1-1/resources/css/ext-all.css"/>
	<script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/extjs/3.4.1-1/adapter/ext/ext-base.js"></script>
	<script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/extjs/3.4.1-1/ext-all.js"></script>

	
	<link rel="stylesheet" type="text/css" href="http://cdnjs.cloudflare.com/ajax/libs/openlayers/2.12/theme/default/style.css"/>
 	<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>

	
	<script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/openlayers/2.12/OpenLayers.js"></script>

	
	<script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/geoext/1.1/script/GeoExt.js"></script>

	
	<script type="text/javascript" src="../../ux/gxp/gxp.js"></script>
	<link rel="stylesheet" type="text/css" href="../../ux/gxp/git/src/theme/all.css"/>
	
	
	<link rel="stylesheet" type="text/css" href="../../resources/css/default.css"/>
	<script type="text/javascript" src="../../script/Heron.js"></script>

	<script type="text/javascript" src="Config.js"></script>
</head>
<body>

</body>
</html>

I also try with extjs 2.13.1 and nothing...
Thanks el486.

**Comment by dracic** [comment]
Can you turn on developer tools (refresh after that) in Chrome and past here if something pops out in 'Console'?

**Comment by gzkii27** [comment]
OK dracic output is this:

Starting Heron v1.0.5 - Proxy URL="/cgi-bin/proxy.cgi?url=" - Service URL="/cgi-bin/heron.cgi"
Creating Heron App from layout = panel
Google Maps API warning: SensorNotRequired: https://developers.google.com/maps/documentation/javascript/error-messages

![image](https://cloud.githubusercontent.com/assets/11275130/12174921/5b87a774-b52d-11e5-88ae-e11c934d76a5.png)

**Comment by dracic** [comment]
Ok, one more time with that WMS layer...

**Comment by gzkii27** [comment]
mmm I retired google maps api warning (sensor tag) and now my console output is this:

Starting Heron v1.0.5 - Proxy URL="/cgi-bin/proxy.cgi?url=" - Service URL="/cgi-bin/heron.cgi"
Heron.js:179 Creating Heron App from layout = panel
OpenLayers.js:1063 Uncaught TypeError: Cannot read property 'style' of undefinedOpenLayers.Layer.Google.v3.repositionMapElements @ OpenLayers.js:1063(anonymous function) @ OpenLayers.js:62

**Comment by dracic** [comment]
```
https://trac.osgeo.org/openlayers/wiki/SettingZoomLevels
```

**Comment by dracic** [comment]
I use scales instead of resolutions, and use EPSG:3765. I had similar problems, and as I can remember they were solved by adding resolutions or scales:

```
OpenLayers.DOTS_PER_INCH = 90.71428571428572;
OpenLayers.IMAGE_RELOAD_ATTEMPTS = 2;
OpenLayers.Util.onImageLoadErrorColor = "transparent";

OpenLayers.Projection.defaults['EPSG:3765'] = {
	yx : false
};


Ext.namespace("Heron.options.map");
Heron.options.map.settings = {
	projection : 'EPSG:3765',
	units : 'm',
	scales : [5000000, 2500000, 1000000, 500000, 250000, 100000, 50000, 25000, 10000, 5000, 2500, 1000/*, 500*/],
	//resolutions: [1400.0028000056, 700.0014000028, 280.00056000112, 140.00028000056, 70.00014000028, 28, 14.000028000055996, 7, 2.8, 1.4, 0.5599999999999999, 0.27999999999999997/*, 0.14, 0.07, 0.028*/],
	maxExtent : '250515, 4694487, 747013, 5163391',
	center : '498764,4928939',
	xy_precision : 3,
	zoom : 0,
	theme : null,
	transitionEffect : 'resize',
	tileManager : null,

	/**
	 * Useful to always have permalinks enabled. default is enabled with these settings.
	 * MapPanel.getPermalink() returns current permalink
	 **/
	permalinks : {
		/** The prefix to be used for parameters, e.g. map_x, default is 'map' */
		paramPrefix : 'map',
		/** Encodes values of permalink parameters ? default false*/
		encodeType : false,
		/** Use Layer names i.s.o. OpenLayers-generated Layer Id's in Permalinks */
		prettyLayerNames : true
	},

	/**  Dodatne OpenLayers kontrole */
	controls : [new OpenLayers.Control.Attribution(), 
	new OpenLayers.Control.ZoomBox(), 
	new OpenLayers.Control.Navigation({
		dragPanOptions : {
			enableKinetic : true
		}
	}), new OpenLayers.Control.LoadingPanel(), 
	new OpenLayers.Control.PanPanel(), 
	new OpenLayers.Control.ZoomPanel(),
	new OpenLayers.Control.ScaleLine({
		geodesic : true,
		maxWidth : 200
	})]
};
```

**Comment by gzkii27** [comment]
Hi guys i solved the problem :):):).

the mistake was easy but too difficult to detect:
in the config file i use map extent:

maxExtent: '-8411534, -8383950, 949191, 925030'

is a mistake because correct format is: maxExtent: 'minX, minY, maxX, maxY'

in that case maxExtent is:

maxExtent: '-8411534, 925030, -8383950, 949191'

this caused the problem...
i can´t detected quickly because the map continue displaying and working...

on the other hand google maps image are very poor in my aoi for that reason i load a satellite image as base layer as backing (although it is a bit heavy)
now my app look like this

![image](https://cloud.githubusercontent.com/assets/11275130/12594697/58f45f26-c445-11e5-8f92-020bbf9948e3.png)

Thank you guys, possible see in foos4g 2016...
