### ISSUE TITLE
Oleditor - Croatian translation not present in heron/master

### ISSUE THREAD

**Issue by dracic** [heron-mc/heron-mc#447]
I think submodule for oleditor is not updated with the latest commit, so Croatian translation for oleditor is not present in heron/master nor in the Heron build.

**Comment by justb4** [comment]
Strange, I may not be using the right commands to update Git submodules? But in the ``ole.min.js`` I see that Croatian is present:

     grep peterokut ole.min.js 
 ``oleDrawRegularSides5:"peterokut",oleDrawRegularSides6:"šesterokut",oleDrawRegularCircle:"kružnica",oleImportFeature:"Uvezi označen objekt",oleImportFeatureSourceLayer:"Nije pronađen izvorišni sloj",oleImportFeatureSourceFeature:"Prvo označi objekt.",oleLayerSettingsImportHeader:"Uvezi",oleLayerSettingsImportLabel:"Koristi kao izvorišni sloj",oleLayerSettingsLegendHeader:"Legenda",oleLayerSettingsOpacityHeader:"Prozirnost (%)",oleMergeFeature:"Spoji označene objekte",oleMergeFeatureSelectFeature:"Označi najmanje dva objekta.",``

**Comment by dracic** [comment]
You probably have latest commit (4657115) in your local heron repo, and you've got ole.min.js right but you've probably haven't added ole submodule to index, just ole.min.js when you commited locally and pushed that change to heron. So we're still on 06a83ff

**Comment by dracic** [comment]
It is not a big problem, but if someone does his own build of Heron, latest ole changes will not be present...

**Comment by justb4** [comment]
Updated the ole submodule. I hope. Git Submodules are confusing sometimes...

**Comment by dracic** [comment]
Thanks. Now we have corect commit for ole submodule...
