### ISSUE TITLE
featureinfo not working

### ISSUE THREAD

**Issue by irshan9908** [heron-mc/heron-mc#471]
hi.. i am completely new to programming with only a basic knowledge. i have managed to create a geoportal by stiching together strings of codes from heron mapping client examples. however the feature info panel seems not be working at all. every time the info button is clicked the panel returns text "no features found" can anyone suggest what to do... i am attaching the index. html file as well as the config.js file for inspection

[Config.txt](https://github.com/heron-mc/heron-mc/files/1180379/Config.txt)
[index.txt](https://github.com/heron-mc/heron-mc/files/1180378/index.txt)

**Comment by el486** [comment]
Reproyection issue? You may want to check the content of the info request in chrome console->network tab (hit f12 to open it)
Here is how it sould look (i´m using epsg 900913)

http://www.mosp.gba.gov.ar/sig_hidraulica/ms/geoserver/dipsoh/gwc/service/wms?LAYERS=dipsoh%3Adepartamentos&QUERY_LAYERS=dipsoh%3Adepartamentos&STYLES=&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetFeatureInfo&BBOX=-7524256.178879%2C-4784148.039255%2C-5475743.821121%2C-4202003.631916&FEATURE_COUNT=8&HEIGHT=476&WIDTH=1675&FORMAT=image%2Fpng&INFO_FORMAT=application%2Fvnd.ogc.gml&SRS=EPSG%3A900913&X=579&Y=320


Try reproyecting the layers in geoserver to match the request proyection

**Comment by justb4** [comment]
Apart from that: is your proxy script working?
in Config.txt:
OpenLayers.ProxyHost = "/cgi-bin/proxy.cgi?url="
A proxy script is needed for all info requests (GetFeatureInfo, WFS etc)
going to a different origin (URL) than where your Heron app is hosted.
Best,

Just

**Comment by irshan9908** [comment]
thank you very much guys.... sorry couldn't cmmnt earlier. but the issue was solved by modifying the proxy.cgi file... thanks for all inputs
