### ISSUE TITLE
Are pull requests welcome?

### ISSUE THREAD

**Issue by MarcoDuiker** [heron-mc/heron-mc#486]
When fixing bugs in Heron I'd like that my efforts benefit others. For this I'd like to submit pull request (I admit that I am severely lagging behind on that), but ... I see that the latest merged pull request (other than the addition of a language file in 2018) is from 2016.

Before spending time on creating the more complex pull requests, I'd like to see some clarification.

Are pull requests welcome? Is there any use in submitting pull requests?

If we take this (https://www.fpcomplete.com/blog/2018/07/guide-to-open-source-maintenance) as a guide, which maintenance level should we expect?

Thank you for any clarifications, MArco

**Comment by justb4** [comment]
We're still happy to accept PRs. So support level is in between **Dedicated** and **Happy to Merge**. Given busy schedules, it may be that PRs are not immediately applied. We need to test if a PR does not break anything, takes time.

**Comment by justb4** [comment]
So yes, welcome. Though reviewers may sometimes be strict in order to guard quality. 😉

**Comment by MarcoDuiker** [comment]
I would be very disappointed if the reviewers weren't strict!
